server.port=8080

# Permite patrones regex en @GetMapping (necesario para SpaController)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Perfil activo por defecto
spring.profiles.active=dev
